server {
    listen 80;
    listen [::]:80;

    server_name eat-it.space www.eat-it.space;

    root /var/www/eat-it/dist/eat_it_ng/browser;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(?:css|js|ico|png|jpg|jpeg|gif|svg|webp|woff2?)$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }
}
